sonarqube {
    properties {
        property "sonar.projectKey", "my-project-key"
        property "sonar.host.url", "http://localhost:9000"
        property "sonar.login", "-----BEGIN RSA PRIVATE KEY-----
MIIEpAIBAAKCAQEA76yC+LoEyuDZca+yRQ8tYm0Q9GHpH+G4OS83TbCtaYO+ngFC
akHlV9ZbRsyjr/wLiRWXMiQbQnYZsCnR7tfhiP4T2063tBXzkJXESsYbcvM4aL44
PESdWQqQJkSWxzwMk9s9UCyJwDYMPMfC010C5f5w2ULhpQRzlRYkWDVcAFJb2WHZ
yHkXyG976joMmZe1mkuMDLqoetWInd8yamxNU20dlV2AuIqTY6y5cKlfw6KpDty2
EqN+3cirbMCepZwB+rWllaQxJPVz8bRGJ4ayxpjSWWyYXdzVY6uVLUkW2y9v8tSC
DoYpGNlHVPb8Ci9ClI9oe1Z7iU0yTGTfflCPtQIDAQABAoIBAQDUFMswXSqwe5bu
SpJtGakHV4uRNLKdS5dAws8lKBnLLJEYL/UdIYJX346Vb6/Iojdy7nAEJn8YqHjC
sb7aop0oI+xeO6HC8Um9v0kbAYJ4jVB1Hx2T9wNlLzuvITJqynA2xeHTeBXMyAa8
Ief8MGnIKwagudYBt5avbhBrHYxzmrbTTSCVdWtPvsxkF869JRQqubWXHdDiLDCi
uxU0PNj7g/9t1OKVk9spV4sFRwu3peNMh8UF7Cjml/jPHtVJZesf9n8tbw2TgZPO
/KmL3j+esVQBGTwO35C4G65FxcXJXCjYZnVNBeS4Ve+dxGfwnwngrEuiuVVRd2aP
VGFZE1VhAoGBAPqs+1jTlVBr1+Gnr+7sOn4zrqPVxYJbRtaumfrDa0JhkeN+UiGL
2hQIrwissSbE0XuHgrvKtNK8bRzZuXufFIn2wJn9OFxDDHDyxAdCQGlq/0pCNCdC
FQT/0MT5rL9UbLV1LrbR5uIJuc4EddDn4rjOngl/m6yq1cVRocy4U/3rAoGBAPTD
tWqFIDwpYDXGfnMMKytA1cNglEd/BwBo6jXask1V8/hKKWxWFfRwD+3f9yimc4tQ
tI3opYouI01r+Ig85oR0rRyrrQKat+00MRUCaReKoqqVPMNJW0HA2whGl6oh7Vge
KIp9F/ovh9Sfjr1aIwgh4F2KK1uEZFHvBj1o+yDfAoGBANlNkyXRZSKuGhq3rr/D
cIFuc/n6mpkCX0pDWaAUP6rvwfQf0TrbbVToojM24Ormu2IGesIoWtBEH6Je63fK
05c1nIjhBjaUuPhAusZAHG5GHsBU27kcg/QtfuECP0os+X/j8XbyRt+z5qo9G5TZ
L6VdF4rMYDsybNX8ifJZ6BW5AoGAKEDPYxdFt98uHWnpfc4wg0qEXT9S43c2lZCr
g/PVgvZxyxGXQmPd9HdBh2Nf6GWHdw/swbHTF6iC0cbB9tXdK0ds+Nwa9eSv/uio
ccYVtnNsURV+CrfTtDqdSv0hEC/IMsey7yOnf9O1SPh8pxNd04aOuZNxkflx7i+b
HRpYwo0CgYALPsTWl/CrrhwJnoQ/f+fys5luFpMeJB9FZdBZMW7mRKKjqc4voF8H
3y81gg7jfp0cgyJnIWJpj8gHF7mTeMn6MoXCKN9oFS1cmeErL2z4BvKyRg40O7Do
4wU8eF9+IftW2rnH1e+oCu5kMZ92Br4mXDCmluw99CtqJ81RXMv5gg==
-----END RSA PRIVATE KEY-----
"
        property "sonar.sources", "src,lpcs"   // lpcs 포함
    }
}
