# 프로젝트 식별
sonar.organization=Holybranch    # SonarCloud 계정 조직키
sonar.projectKey=Holybranch_code # 프로젝트 키 (SonarCloud에서 확인 가능)

# 분석할 소스 코드 위치
sonar.sources=.

# 선택 사항: 빌드 언어나 테스트
# sonar.language=py
# sonar.tests=tests
