name: SonarCloud Analysis

on:
  push:
    branches: ["main"]   # main 브랜치 push 시 분석
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      # 1. 코드 체크아웃
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2. SonarCloud 스캔
      - name: Run SonarCloud
        uses: SonarSource/sonarqube-scan-action@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ c77ebcb5e4b880f900c1f3e58890ca042e8e57ca }}
